/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finter.finter.vistas;

import java.util.ArrayList;
import java.util.Collection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Propietario
 */
public class Principal2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Principal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabelAlgoritmoSeleccioando = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaDeDatos = new javax.swing.JTable();
        jButtonIngresar = new javax.swing.JButton();
        jButtonMostrarPASOS = new javax.swing.JButton();
        jButtonEspecializarPolinomio = new javax.swing.JButton();
        jButtonAlterarValoresIniciales = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("FINTER");

        label2.setText("Algoritmo seleccionado");

        jLabelAlgoritmoSeleccioando.setText("Lagrange");

        jTablaDeDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Dominio", "Imagen"
            }
        ));
        jScrollPane2.setViewportView(jTablaDeDatos);

        jButtonIngresar.setText("INGRESAR DATOS");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        jButtonMostrarPASOS.setText("MOSTRAR PASOS DE CALCULO");

        jButtonEspecializarPolinomio.setText("ESPECIALIZAR POLINOMIO");

        jButtonAlterarValoresIniciales.setText("ALTERAR VALORES INICIALES");

        jButton5.setText("FINALIZAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlgoritmoSeleccioando)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMostrarPASOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEspecializarPolinomio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAlterarValoresIniciales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAlgoritmoSeleccioando)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMostrarPASOS)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEspecializarPolinomio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterarValoresIniciales)
                        .addGap(103, 103, 103)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed

        IngresarDatos ingresodedatos = new IngresarDatos(this, jLabelAlgoritmoSeleccioando.getText());
        ingresodedatos.activar(this, jLabelAlgoritmoSeleccioando.getText());

    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }
    
    private void crearTabla(){
        DefaultTableModel model;
        model = new javax.swing.table.DefaultTableModel(
                        new Object [][] {},  
                        new String [] {"X", "f(X)"});
        jTablaDeDatos.setModel(model);
    }
    
    public Collection<Integer> obtenerTodoX(){
        Collection<Integer> datos = new ArrayList<Integer>();
        int i;
        DefaultTableModel model =  (DefaultTableModel)jTablaDeDatos.getModel();
        for(i=0; i< model.getRowCount();i++){
            datos.add(Integer.parseInt(model.getValueAt(i, 1).toString()));
        }
        return datos;
    }
    
    public String obtenerTipoAlgoritmo(){
        return jLabelAlgoritmoSeleccioando.getText();
    }
    
    public Collection<Integer> obtenerTodoY(){
        Collection<Integer> datos = new ArrayList<Integer>();
        int i;
        DefaultTableModel model =  (DefaultTableModel)jTablaDeDatos.getModel();
        for(i=0; i< model.getRowCount();i++){
            datos.add(Integer.parseInt(model.getValueAt(i, 2).toString()));
        }
        return datos;
    }
    
    public void ingresoDeAlgoritmo(String algoritmo){
        jLabelAlgoritmoSeleccioando.setText(algoritmo);
    }
    
    public boolean ingresoDeDatos(int x, int y){
        DefaultTableModel model =  (DefaultTableModel)jTablaDeDatos.getModel();
        int i;
        for(i=0; i< model.getRowCount();i++){
            if(Integer.parseInt(model.getValueAt(i, 0).toString()) == x){
                return false;
            }
        }
        //INGRESO DE NUEVO PAR DE DATOS
        Object[] row = new Object[4];
        row[0]=x;
        row[1]=y;
        model.addRow(row);
        //QUIZAS SI SE TIENE GANAS SE ORDENA LA LISTA
        return true;
    }
    
    public void activar() {
      //   pedirUser();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAlterarValoresIniciales;
    private javax.swing.JButton jButtonEspecializarPolinomio;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonMostrarPASOS;
    private javax.swing.JLabel jLabelAlgoritmoSeleccioando;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaDeDatos;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
